export type LlamacppOptionType = "text" | "number" | "boolean" | "select";

export type LlamacppOption = {
  key: string;
  label: string;
  type: LlamacppOptionType;
  tab: "model" | "resources" | "performance" | "features";
  placeholder?: string;
  options?: string[];
  description?: string;
};

export const LLAMACPP_OPTIONS: LlamacppOption[] = [
  {
    key: "model-url",
    label: "Model URL",
    type: "text",
    tab: "model",
    placeholder: "https://.../model.gguf",
  },
  {
    key: "hf-repo",
    label: "HF Repo",
    type: "text",
    tab: "model",
    placeholder: "org/model",
  },
  {
    key: "hf-file",
    label: "HF File",
    type: "text",
    tab: "model",
    placeholder: "model.gguf",
  },
  {
    key: "hf-token",
    label: "HF Token",
    type: "text",
    tab: "model",
    placeholder: "hf_...",
  },
  {
    key: "hf-cache",
    label: "HF Cache Dir",
    type: "text",
    tab: "model",
    placeholder: "/models/cache",
  },
  {
    key: "lora",
    label: "LoRA",
    type: "text",
    tab: "model",
    placeholder: "/path/to/lora.gguf",
  },
  {
    key: "lora-scaled",
    label: "LoRA (Scaled)",
    type: "text",
    tab: "model",
    placeholder: "/path/to/lora.gguf,scale",
  },
  {
    key: "control-vector",
    label: "Control Vector",
    type: "text",
    tab: "model",
    placeholder: "/path/to/control-vector.bin",
  },
  {
    key: "control-vector-scaled",
    label: "Control Vector (Scaled)",
    type: "text",
    tab: "model",
    placeholder: "/path/to/control-vector.bin,scale",
  },
  {
    key: "control-vector-layer-range",
    label: "Control Vector Layers",
    type: "text",
    tab: "model",
    placeholder: "start,end",
  },
  {
    key: "chat-template",
    label: "Chat Template",
    type: "text",
    tab: "model",
  },
  {
    key: "chat-template-file",
    label: "Chat Template File",
    type: "text",
    tab: "model",
  },
  {
    key: "system-prompt",
    label: "System Prompt",
    type: "text",
    tab: "model",
  },
  {
    key: "prompt",
    label: "Prompt",
    type: "text",
    tab: "model",
  },
  {
    key: "prompt-file",
    label: "Prompt File",
    type: "text",
    tab: "model",
  },
  {
    key: "grammar",
    label: "Grammar",
    type: "text",
    tab: "model",
  },
  {
    key: "grammar-file",
    label: "Grammar File",
    type: "text",
    tab: "model",
  },
  {
    key: "ctx-size",
    label: "Context Size Override",
    type: "number",
    tab: "model",
    placeholder: "8192",
  },
  {
    key: "rope-scaling",
    label: "RoPE Scaling",
    type: "select",
    tab: "model",
    options: ["none", "linear", "yarn"],
  },
  {
    key: "rope-scale",
    label: "RoPE Scale",
    type: "number",
    tab: "model",
  },
  {
    key: "rope-freq-base",
    label: "RoPE Freq Base",
    type: "number",
    tab: "model",
  },
  {
    key: "rope-freq-scale",
    label: "RoPE Freq Scale",
    type: "number",
    tab: "model",
  },
  {
    key: "yarn-orig-ctx",
    label: "YaRN Orig Ctx",
    type: "number",
    tab: "model",
  },
  {
    key: "yarn-ext-factor",
    label: "YaRN Ext Factor",
    type: "number",
    tab: "model",
  },
  {
    key: "yarn-attn-factor",
    label: "YaRN Attn Factor",
    type: "number",
    tab: "model",
  },
  {
    key: "yarn-beta-fast",
    label: "YaRN Beta Fast",
    type: "number",
    tab: "model",
  },
  {
    key: "yarn-beta-slow",
    label: "YaRN Beta Slow",
    type: "number",
    tab: "model",
  },
  {
    key: "gpu-layers",
    label: "GPU Layers",
    type: "number",
    tab: "resources",
    placeholder: "99",
  },
  {
    key: "gpu-layers-draft",
    label: "GPU Layers (Draft)",
    type: "number",
    tab: "resources",
  },
  {
    key: "split-mode",
    label: "Split Mode",
    type: "select",
    tab: "resources",
    options: ["none", "layer", "row"],
  },
  {
    key: "tensor-split",
    label: "Tensor Split",
    type: "text",
    tab: "resources",
    placeholder: "1,1,1,1",
  },
  {
    key: "main-gpu",
    label: "Main GPU",
    type: "number",
    tab: "resources",
  },
  {
    key: "cache-type-k",
    label: "KV Cache Type (K)",
    type: "select",
    tab: "resources",
    options: ["f16", "q8_0", "q4_0", "q6_K"],
  },
  {
    key: "cache-type-v",
    label: "KV Cache Type (V)",
    type: "select",
    tab: "resources",
    options: ["f16", "q8_0", "q4_0", "q6_K"],
  },
  {
    key: "cache-type-k-draft",
    label: "KV Cache Type K (Draft)",
    type: "select",
    tab: "resources",
    options: ["f16", "q8_0", "q4_0", "q6_K"],
  },
  {
    key: "cache-type-v-draft",
    label: "KV Cache Type V (Draft)",
    type: "select",
    tab: "resources",
    options: ["f16", "q8_0", "q4_0", "q6_K"],
  },
  {
    key: "no-kv-offload",
    label: "Disable KV Offload",
    type: "boolean",
    tab: "resources",
  },
  {
    key: "no-mmap",
    label: "Disable mmap",
    type: "boolean",
    tab: "resources",
  },
  {
    key: "mlock",
    label: "Lock Memory",
    type: "boolean",
    tab: "resources",
  },
  {
    key: "numa",
    label: "NUMA",
    type: "boolean",
    tab: "resources",
  },
  {
    key: "threads",
    label: "Threads",
    type: "number",
    tab: "performance",
  },
  {
    key: "threads-batch",
    label: "Threads (Batch)",
    type: "number",
    tab: "performance",
  },
  {
    key: "threads-http",
    label: "Threads (HTTP)",
    type: "number",
    tab: "performance",
  },
  {
    key: "batch-size",
    label: "Batch Size",
    type: "number",
    tab: "performance",
  },
  {
    key: "ubatch-size",
    label: "Micro Batch Size",
    type: "number",
    tab: "performance",
  },
  {
    key: "parallel",
    label: "Parallel Slots",
    type: "number",
    tab: "performance",
  },
  {
    key: "cpu-mask",
    label: "CPU Mask",
    type: "text",
    tab: "performance",
  },
  {
    key: "cpu-range",
    label: "CPU Range",
    type: "text",
    tab: "performance",
  },
  {
    key: "prio",
    label: "CPU Priority",
    type: "number",
    tab: "performance",
  },
  {
    key: "poll",
    label: "Poll",
    type: "number",
    tab: "performance",
  },
  {
    key: "poll-batch",
    label: "Poll Batch",
    type: "number",
    tab: "performance",
  },
  {
    key: "samplers",
    label: "Samplers",
    type: "text",
    tab: "features",
    placeholder: "top-k;top-p;min-p;temp",
  },
  {
    key: "temp",
    label: "Temperature",
    type: "number",
    tab: "features",
  },
  {
    key: "top-k",
    label: "Top K",
    type: "number",
    tab: "features",
  },
  {
    key: "top-p",
    label: "Top P",
    type: "number",
    tab: "features",
  },
  {
    key: "min-p",
    label: "Min P",
    type: "number",
    tab: "features",
  },
  {
    key: "typical",
    label: "Typical P",
    type: "number",
    tab: "features",
  },
  {
    key: "repeat-last-n",
    label: "Repeat Last N",
    type: "number",
    tab: "features",
  },
  {
    key: "repeat-penalty",
    label: "Repeat Penalty",
    type: "number",
    tab: "features",
  },
  {
    key: "presence-penalty",
    label: "Presence Penalty",
    type: "number",
    tab: "features",
  },
  {
    key: "frequency-penalty",
    label: "Frequency Penalty",
    type: "number",
    tab: "features",
  },
  {
    key: "mirostat",
    label: "Mirostat",
    type: "number",
    tab: "features",
  },
  {
    key: "mirostat-lr",
    label: "Mirostat LR",
    type: "number",
    tab: "features",
  },
  {
    key: "mirostat-ent",
    label: "Mirostat Entropy",
    type: "number",
    tab: "features",
  },
  {
    key: "ignore-eos",
    label: "Ignore EOS",
    type: "boolean",
    tab: "features",
  },
  {
    key: "logit-bias",
    label: "Logit Bias",
    type: "text",
    tab: "features",
    placeholder: "token=weight,token=weight",
  },
  {
    key: "n-predict",
    label: "Max Tokens",
    type: "number",
    tab: "features",
  },
  {
    key: "n-keep",
    label: "Tokens to Keep",
    type: "number",
    tab: "features",
  },
  {
    key: "api-key",
    label: "API Key",
    type: "text",
    tab: "features",
  },
];

export const LLAMACPP_OPTION_KEYS = LLAMACPP_OPTIONS.map((option) => option.key);
