import type { StudioModelRecommendation } from "./types";

export const STUDIO_MODEL_RECOMMENDATIONS: StudioModelRecommendation[] = [
  {
    id: "meta-llama/Llama-4-Maverick-17B-128E-Instruct",
    name: "Llama 4 Maverick 17Bx128E",
    size_gb: 160,
    min_vram_gb: 140,
    description: "Meta's latest MoE flagship — 400B+ params, top-tier reasoning.",
    tags: ["chat", "reasoning", "flagship"],
  },
  {
    id: "Qwen/Qwen3-235B-A22B",
    name: "Qwen3 235B (A22B MoE)",
    size_gb: 150,
    min_vram_gb: 130,
    description: "Qwen's largest MoE model with thinking/non-thinking modes.",
    tags: ["chat", "reasoning", "multilingual", "flagship"],
  },
  {
    id: "deepseek-ai/DeepSeek-R1",
    name: "DeepSeek R1",
    size_gb: 160,
    min_vram_gb: 140,
    description: "Top-tier open reasoning model, 671B MoE.",
    tags: ["reasoning", "code", "flagship"],
  },
  {
    id: "meta-llama/Llama-4-Scout-17B-16E-Instruct",
    name: "Llama 4 Scout 17Bx16E",
    size_gb: 38,
    min_vram_gb: 34,
    description: "Efficient Llama 4 MoE variant with 10M token context.",
    tags: ["chat", "long-context", "recommended"],
  },
  {
    id: "Qwen/Qwen3-32B",
    name: "Qwen3 32B",
    size_gb: 64,
    min_vram_gb: 48,
    description: "Dense 32B with built-in thinking — strong all-rounder.",
    tags: ["chat", "reasoning", "code", "recommended"],
  },
  {
    id: "meta-llama/Llama-3.3-70B-Instruct",
    name: "Llama 3.3 70B Instruct",
    size_gb: 140,
    min_vram_gb: 80,
    description: "Latest Llama 3.3 dense model, excellent instruction following.",
    tags: ["chat", "general", "recommended"],
  },
  {
    id: "mistralai/Mistral-Small-24B-Instruct-2501",
    name: "Mistral Small 24B",
    size_gb: 48,
    min_vram_gb: 32,
    description: "Mistral's latest efficient model with strong tool use.",
    tags: ["chat", "tool-use", "fast"],
  },
  {
    id: "google/gemma-3-27b-it",
    name: "Gemma 3 27B",
    size_gb: 54,
    min_vram_gb: 40,
    description: "Google's latest open model — multilingual, vision-ready.",
    tags: ["chat", "multilingual", "vision"],
  },
  {
    id: "Qwen/Qwen3-14B",
    name: "Qwen3 14B",
    size_gb: 28,
    min_vram_gb: 20,
    description: "Great quality-to-size ratio with thinking mode.",
    tags: ["chat", "reasoning", "fast"],
  },
  {
    id: "meta-llama/Llama-3.1-8B-Instruct",
    name: "Llama 3.1 8B",
    size_gb: 16,
    min_vram_gb: 12,
    description: "Fast and reliable for single-GPU setups.",
    tags: ["chat", "fast", "starter"],
  },
  {
    id: "Qwen/Qwen3-8B",
    name: "Qwen3 8B",
    size_gb: 16,
    min_vram_gb: 12,
    description: "Compact model with thinking and tool-use support.",
    tags: ["chat", "reasoning", "fast", "starter"],
  },
  {
    id: "microsoft/Phi-4",
    name: "Phi-4 14B",
    size_gb: 28,
    min_vram_gb: 20,
    description: "Microsoft's latest small-but-capable reasoning model.",
    tags: ["chat", "reasoning", "code"],
  },
];
