/**
 * Central icon barrel — the single import source for all icons in the app.
 *
 * Re-exports every lucide-react icon used across the codebase plus the custom
 * solid SVG set from icons.tsx. All files should import from here instead of
 * directly from "lucide-react", so the visual style can be changed in one place.
 */
export type { LucideIcon } from "lucide-react";

// Custom solid SVG icons (agent surface)
export {
  ChatIcon,
  PinIcon,
  PlusIcon,
  CloseIcon,
  TrashIcon,
  ChevronDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ReloadIcon,
  SendIcon,
  StopIcon,
  FileIcon,
  GlobeIcon,
  GitBranchIcon,
  EyeOffIcon,
  SitegeistIcon,
  PanelIcon,
  MoreIcon,
  Folder,
  FolderOpen,
} from "./icons";

// Lucide-react re-exports — all icons used across the app
export {
  Activity,
  AlertCircle,
  AlertTriangle,
  Archive,
  ArrowUpCircle,
  AtSign,
  Boxes,
  Brain,
  Cable,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleDot,
  Clock,
  Code,
  Code2,
  Compass,
  Copy,
  Cpu,
  Database,
  Download,
  DownloadCloud,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileText,
  Filter,
  FolderTree,
  Gauge,
  GitBranch,
  GitFork,
  Globe,
  Globe2,
  GraduationCap,
  HardDrive,
  Heart,
  Info,
  Laptop,
  Layers,
  LayoutDashboard,
  Link,
  ListChecks,
  Circle,
  Loader2,
  LoaderCircle,
  Menu,
  MessageCircle,
  MessageSquare,
  MessageSquarePlus,
  Microchip,
  Minus,
  Monitor,
  Moon,
  MoreVertical,
  Network,
  Paintbrush,
  PanelLeftClose,
  PanelLeftOpen,
  PanelRight,
  PanelRightClose,
  PanelRightOpen,
  Pause,
  Play,
  Plus,
  RefreshCw,
  Rocket,
  RotateCcw,
  Save,
  Search,
  Server,
  ServerCog,
  Settings,
  ShieldCheck,
  Slash,
  Sparkles,
  Square,
  SquarePen,
  Sun,
  Tags,
  Terminal,
  TerminalSquare,
  TrendingUp,
  TriangleAlert,
  Trash2,
  Variable,
  Wrench,
  X,
  XCircle,
  Zap,
  Plug,
  PlugZap,
} from "lucide-react";
